### ISSUE TITLE
pcrglobwb BMI seems broken

### ISSUE THREAD

**Issue by BSchilperoort** [eWaterCycle/ewatercycle-pcrglobwb#1]
Model setup initialization and update go fine. However, when trying to use the get_value_as_xarray method, the bmi breaks:
```
	details = "Exception calling application: 'BmiPCRGlobWB' object has no attribute 'get_grid_size'"
```

Other BMI methods seems broken as wel, such as **get_value** or **get_var_type**:
```
	details = "Exception calling application: <type 'numpy.float32'> has type type, but expected one of: bytes, unicode"
```

**Edit**: note that methods such as `output_var_names` do work.

@sverhoeven :confused:?

**Comment by BSchilperoort** [comment]
Is there a BMI version conflict here?

**Comment by Peter9192** [comment]
Did you get this with an existing container or did you build a new one?

**Comment by BSchilperoort** [comment]
> Did you get this with an existing container or did you build a new one?

Existing one, sadly. I am not sure if that grpc4bmi server version is compatible with the current client.

**Comment by BSchilperoort** [comment]
Looking at the dockerfiles:
- Very old BMI is used (which doesn't work anymore with the current client) 
  - https://github.com/eWaterCycle/grpc4bmi-examples/tree/master/pcrglob
- Tried updating this: old python is used in the parent images, so the latest grpc4bmi cannot be installed. I'll have to dig deeper

**Comment by BSchilperoort** [comment]
These are the docker images:

1. https://github.com/eWaterCycle/pcraster-container/blob/master/Dockerfile
2. https://github.com/eWaterCycle/PCR-GLOBWB_model/blob/bmi_fixes_setters/Dockerfile
3. https://github.com/eWaterCycle/grpc4bmi-examples/blob/master/pcrglob/Dockerfile

**Comment by Peter9192** [comment]
Note that the to_xarray method was generalized in https://github.com/eWaterCycle/ewatercycle/commit/92cd6160b06fdf4b000056282e489fc82c65f576#diff-0d2fbbaab6c5ef022430f151dc1fecd52efee0de42a2615e81e2aa01786c193c. 

In looking for how it ever worked before, I think I'd start there

**Comment by BSchilperoort** [comment]
The problem is that `get_value` or `get_var_type` are also broken... Without being able to get the value, the to_xarray method can never work.

**Comment by Peter9192** [comment]
Just a guess from the couch: Is it possible that optionaldestbmi creates a destination array with the wrong/incompatible type? This is a relatively recent addition compared to how we've been using pcrglob before

**Comment by BSchilperoort** [comment]
> Just a guess from the couch: Is it possible that optionaldestbmi creates a destination array with the wrong/incompatible type? This is a relatively recent addition compared to how we've been using pcrglob before

`get_var_type` gives the same error...

**Comment by BSchilperoort** [comment]
OK I've figured out what works and what doesn't. 

We _can_ actually get the values, but `get_grid_size` is not implemented.

According to the BMI docs, the required functions for a uniform rectilinear grid are:
 -   get_grid_rank
 -   get_grid_size
  -  get_grid_shape
   - get_grid_spacing
  -  get_grid_origin

These are all implemented _except for_ `get_grid_size`. However, you can work around this using `get_grid_shape` and taking the product of that output.

**Comment by BSchilperoort** [comment]
And problem 2, with `get_var_type`:

https://github.com/eWaterCycle/PCR-GLOBWB_model/blob/e25a07bf63dae0237a7e7039454e96151f9d41c1/model/bmiPcrglobwb.py#L280-L283

This does not return a string, but a numpy type. Which therefore breaks.

**Comment by BSchilperoort** [comment]
The [BMI at UU-Hydro](https://github.com/UU-Hydro/PCR-GLOBWB_model/blob/master/model/bmiPcrglobwb.py) seems more up to date and correct. I will try to rebuild the container(s) from this.

**Comment by BSchilperoort** [comment]
> The [BMI at UU-Hydro](https://github.com/UU-Hydro/PCR-GLOBWB_model/blob/master/model/bmiPcrglobwb.py) seems more up to date and correct. I will try to rebuild the container(s) from this.

I've successfully build a working container, but the config file format seems to have changed since https://github.com/eWaterCycle/PCR-GLOBWB_model/ was forked...
